In [1]:
from bs4 import BeautifulSoup
import pandas as pd
import requests
import re
import time

In [11]:
start_time = time.time()
df=pd.DataFrame(columns=["کلمه کلیدی جستجو","کلمه کلیدی url","نام شغل","مدیریت","توضیحات","شماره تماس","شماره همراه ","منطقه شهرداری ","آدرس ","وب سایت رسمی ","فکس ","ایمیل "])
keyword=input("enter keyword")

r=requests.get("https://asnafyab.ir/search?sw="+keyword)
soup = BeautifulSoup(r.content, 'html.parser')

ul=soup.find("ul", attrs={"class":"pagination"})

if ul!=None:
    print(1111)
    end_page=ul.find_all("a")[-1]
    
    end_page_num=re.findall(r'page=(\d+)',str(end_page))
    end_page_num=str(end_page_num[0])

    for i in range(1,int(end_page_num)+1):
    
        r=requests.get("https://asnafyab.ir/search?sw="+keyword+"&page="+str(i))
        soup = BeautifulSoup(r.content, 'html.parser')    
        h2=soup.find_all("h2",attrs={"class":"JobTitle"})
        print("page :",i)
        
        for hr in h2:
            link=hr.a["href"]

            r=requests.get("https://asnafyab.ir"+str(link))
            soup = BeautifulSoup(r.content, 'html.parser')
            desc=soup.find("div", attrs={"class":"job-desc"})
            a=desc.get_text()

            description=''.join(str(l) for l in a.splitlines()[7:] )   
            job_name=desc.find("div", attrs={"class":"job-name"}).get_text()

            spans=[span for span in desc.find_all("span")]
            mg=spans[0].get_text()
            mg_data=spans[1].get_text()  

            rows=soup.find_all("div", attrs={"class":"job-desc job-contact"})

            l1=rows[0].find_all("div",attrs={"class":"col-sm-3"})
            l2=rows[0].find_all("div",attrs={"class":"col-sm-9"})

            l1_data=[i.get_text() for i in l1]
            l2_data=[i.get_text() for i in l2]
            l1_data=[i.replace(":","") for i in l1_data]
            data=dict(zip(l1_data,l2_data))
            data["توضیحات"]=description
            data["نام شغل"]=job_name
            data["مدیریت"]=mg_data
            link=link.replace("/","")
            data["کلمه کلیدی url"]=link
            data["کلمه کلیدی جستجو"]=keyword
            df = df.append(data, ignore_index=True, sort=False)
            
else:
    print(2222)
    h2=soup.find_all("h2",attrs={"class":"JobTitle"})
    for hr in h2:
        link=hr.a["href"]
        
        r=requests.get("https://asnafyab.ir"+str(link))
        soup = BeautifulSoup(r.content, 'html.parser')
        desc=soup.find("div", attrs={"class":"job-desc"})
        a=desc.get_text()

        description=''.join(str(l) for l in a.splitlines()[7:] )   
        job_name=desc.find("div", attrs={"class":"job-name"}).get_text()

        spans=[span for span in desc.find_all("span")]
        mg=spans[0].get_text()
        mg_data=spans[1].get_text()  

        rows=soup.find_all("div", attrs={"class":"job-desc job-contact"})

        l1=rows[0].find_all("div",attrs={"class":"col-sm-3"})
        l2=rows[0].find_all("div",attrs={"class":"col-sm-9"})

        l1_data=[i.get_text() for i in l1]
        l2_data=[i.get_text() for i in l2]
        l1_data=[i.replace(":","") for i in l1_data]
        data=dict(zip(l1_data,l2_data))
        data["توضیحات"]=description
        data["نام شغل"]=job_name
        data["مدیریت"]=mg_data
        link=link.replace("/","")
        data["کلمه کلیدی url"]=link
        data["کلمه کلیدی جستجو"]=keyword
    

        df = df.append(data, ignore_index=True, sort=False)
print("--- %s seconds ---" % (time.time() - start_time))

enter keyword9121860083
2222
--- 7.200122833251953 seconds ---

In [13]:
df

,کلمه کلیدی جستجو,کلمه کلیدی url,نام شغل,مدیریت,توضیحات,شماره تماس,شماره همراه,منطقه شهرداری,آدرس,وب سایت رسمی,فکس,ایمیل
0,9121860083\t,33982151,نفر اول,سیاوش رضازاده,عرضه بهترین پوشاک مردانه خارجی...,33982151,0912476301109121860083,منطقه 12,\r\n چهارراه استانبول، ...,NaN,NaN,NaN

In [23]:
number=pd.read_excel(r'C:\Users\z.abbasi\Documents\dataset\asnaf_num.xlsx')
df=pd.DataFrame(columns=["کلمه کلیدی جستجو","کلمه کلیدی url","نام شغل","مدیریت","توضیحات","شماره تماس","شماره همراه ","منطقه شهرداری ","آدرس ","وب سایت رسمی ","فکس ","ایمیل "])
num=number["key_word"]
num_range=num.to_list()

for n in num_range:
    r=requests.get("https://asnafyab.ir/search?sw="+str(n))
    soup = BeautifulSoup(r.content, 'html.parser')
    ul=soup.find("ul", attrs={"class":"pagination"})

    if ul!=None:
        end_page=ul.find_all("a")[-1]
        end_page_num=re.findall(r'page=(\d+)',str(end_page))
        end_page_num=str(end_page_num[0])

        for i in range(int(end_page_num)):

            r=requests.get("https://asnafyab.ir/search?sw="+str(n)+"&page="+str(i))
            soup = BeautifulSoup(r.content, 'html.parser')    
            h2=soup.find_all("h2",attrs={"class":"JobTitle"})

            for hr in h2:
                link=hr.a["href"]

                r=requests.get("https://asnafyab.ir"+str(link))
                soup = BeautifulSoup(r.content, 'html.parser')
                desc=soup.find("div", attrs={"class":"job-desc"})
                a=desc.get_text()

                description=''.join(str(l) for l in a.splitlines()[7:] )   
                job_name=desc.find("div", attrs={"class":"job-name"}).get_text()

                spans=[span for span in desc.find_all("span")]
                mg=spans[0].get_text()
                mg_data=spans[1].get_text()  

                rows=soup.find_all("div", attrs={"class":"job-desc job-contact"})

                l1=rows[0].find_all("div",attrs={"class":"col-sm-3"})
                l2=rows[0].find_all("div",attrs={"class":"col-sm-9"})

                l1_data=[i.get_text() for i in l1]
                l2_data=[i.get_text() for i in l2]
                l1_data=[i.replace(":","") for i in l1_data]
                data=dict(zip(l1_data,l2_data))
                data["توضیحات"]=description
                data["نام شغل"]=job_name
                data["مدیریت"]=mg_data
                link=link.replace("/","")
                data["کلمه کلیدی url"]=link
                data["کلمه کلیدی جستجو"]=n
                df = df.append(data, ignore_index=True, sort=False)
    else:

        h2=soup.find_all("h2",attrs={"class":"JobTitle"})
        for hr in h2:
            link=hr.a["href"]

            r=requests.get("https://asnafyab.ir"+str(link))
            soup = BeautifulSoup(r.content, 'html.parser')
            desc=soup.find("div", attrs={"class":"job-desc"})
            a=desc.get_text()

            description=''.join(str(l) for l in a.splitlines()[7:] )   
            job_name=desc.find("div", attrs={"class":"job-name"}).get_text()

            spans=[span for span in desc.find_all("span")]
            mg=spans[0].get_text()
            mg_data=spans[1].get_text()  

            rows=soup.find_all("div", attrs={"class":"job-desc job-contact"})

            l1=rows[0].find_all("div",attrs={"class":"col-sm-3"})
            l2=rows[0].find_all("div",attrs={"class":"col-sm-9"})

            l1_data=[i.get_text() for i in l1]
            l2_data=[i.get_text() for i in l2]
            l1_data=[i.replace(":","") for i in l1_data]
            data=dict(zip(l1_data,l2_data))
            data["توضیحات"]=description
            data["نام شغل"]=job_name
            data["مدیریت"]=mg_data
            link=link.replace("/","")
            data["کلمه کلیدی url"]=link
            data["کلمه کلیدی جستجو"]=n
            #print(keyword)

            df = df.append(data, ignore_index=True, sort=False)

In [24]:
df

,کلمه کلیدی جستجو,کلمه کلیدی url,نام شغل,مدیریت,توضیحات,شماره تماس,شماره همراه,منطقه شهرداری,آدرس,وب سایت رسمی,فکس,ایمیل
0,9121860083,33982151,نفر اول,سیاوش رضازاده,عرضه بهترین پوشاک مردانه خارجی...,33982151,0912476301109121860083,منطقه 12,\r\n چهارراه استانبول، ...,NaN,NaN,NaN
1,9121860093,77933158,تعمیرگاه مجاز آکائی,حسن سلیمیان,تعمیرات دستگاه های صوتی و تصوی...,7793315809121860093,NaN,منطقه 8,\r\n نارمک -خ آیت پلا...,NaN,NaN,NaN
2,9121860137,55631090,اعطاسی,علیرضا اعطاسی,پخش لوازم آشپزخانه,55631090,NaN,منطقه 12,\r\n خ 15 خرداد-بازار آ...,NaN,NaN,NaN

In [27]:
number=input("اعداد اولیه را وارد نمایید")
n1=int(input("اولین رقم شمارنده را وارد کنید"))
n2=int(input("آخرین رقم شمارنده را وارد کنید"))
df=pd.DataFrame(columns=["کلمه کلیدی جستجو","کلمه کلیدی url","نام شغل","مدیریت","توضیحات","شماره تماس","شماره همراه ","منطقه شهرداری ","آدرس ","وب سایت رسمی ","فکس ","ایمیل "])

for n in range(n1,n2):
    r=requests.get("https://asnafyab.ir/search?sw="+str(number)+str(n))
    soup = BeautifulSoup(r.content, 'html.parser')
    ul=soup.find("ul", attrs={"class":"pagination"})

    if ul!=None:
        end_page=ul.find_all("a")[-1]
        end_page_num=re.findall(r'page=(\d+)',str(end_page))
        end_page_num=str(end_page_num[0])

        for i in range(int(end_page_num)):

            r=requests.get("https://asnafyab.ir/search?sw="+str(n)+"&page="+str(i))
            soup = BeautifulSoup(r.content, 'html.parser')    
            h2=soup.find_all("h2",attrs={"class":"JobTitle"})

            for hr in h2:
                link=hr.a["href"]

                r=requests.get("https://asnafyab.ir"+str(link))
                soup = BeautifulSoup(r.content, 'html.parser')
                desc=soup.find("div", attrs={"class":"job-desc"})
                a=desc.get_text()

                description=''.join(str(l) for l in a.splitlines()[7:] )   
                job_name=desc.find("div", attrs={"class":"job-name"}).get_text()

                spans=[span for span in desc.find_all("span")]
                mg=spans[0].get_text()
                mg_data=spans[1].get_text()  

                rows=soup.find_all("div", attrs={"class":"job-desc job-contact"})

                l1=rows[0].find_all("div",attrs={"class":"col-sm-3"})
                l2=rows[0].find_all("div",attrs={"class":"col-sm-9"})

                l1_data=[i.get_text() for i in l1]
                l2_data=[i.get_text() for i in l2]
                l1_data=[i.replace(":","") for i in l1_data]
                data=dict(zip(l1_data,l2_data))
                data["توضیحات"]=description
                data["نام شغل"]=job_name
                data["مدیریت"]=mg_data
                link=link.replace("/","")
                data["کلمه کلیدی url"]=link
                data["کلمه کلیدی جستجو"]=n
                df = df.append(data, ignore_index=True, sort=False)
    else:

        h2=soup.find_all("h2",attrs={"class":"JobTitle"})
        for hr in h2:
            link=hr.a["href"]

            r=requests.get("https://asnafyab.ir"+str(link))
            soup = BeautifulSoup(r.content, 'html.parser')
            desc=soup.find("div", attrs={"class":"job-desc"})
            a=desc.get_text()

            description=''.join(str(l) for l in a.splitlines()[7:] )   
            job_name=desc.find("div", attrs={"class":"job-name"}).get_text()

            spans=[span for span in desc.find_all("span")]
            mg=spans[0].get_text()
            mg_data=spans[1].get_text()  

            rows=soup.find_all("div", attrs={"class":"job-desc job-contact"})

            l1=rows[0].find_all("div",attrs={"class":"col-sm-3"})
            l2=rows[0].find_all("div",attrs={"class":"col-sm-9"})

            l1_data=[i.get_text() for i in l1]
            l2_data=[i.get_text() for i in l2]
            l1_data=[i.replace(":","") for i in l1_data]
            data=dict(zip(l1_data,l2_data))
            data["توضیحات"]=description
            data["نام شغل"]=job_name
            data["مدیریت"]=mg_data
            link=link.replace("/","")
            data["کلمه کلیدی url"]=link
            data["کلمه کلیدی جستجو"]=n
            #print(keyword)

            df = df.append(data, ignore_index=True, sort=False)

اعداد اولیه را وارد نمایید09125590
اولین رقم شمارنده را وارد کنید100
آخرین رقم شمارنده را وارد کنید999

In [28]:
df

,کلمه کلیدی جستجو,کلمه کلیدی url,نام شغل,مدیریت,توضیحات,شماره تماس,شماره همراه,منطقه شهرداری,آدرس,وب سایت رسمی,فکس,ایمیل
0,163,33677506,صنایع چوب شکوفه,قدرت نورپور,تولید و پخش مدرن ترین میزهای ص...,33677506,09125590163,منطقه 14,\r\n خ 17 شهریور، خ شکو...,NaN,NaN,NaN
1,247,55154587,سارینا,عباس لواسانی,پوشاک مردانه,55154587,NaN,منطقه 12,\r\n 15خرداد-بازارآهنگر...,NaN,NaN,NaN
2,316,09125590316,باطری سازی شاهین,فضل اله عقیقی,سیم کشی، استارت، تعمیر دینام ...,,09125590316,منطقه 14,\r\n اتوبان شهید محلاتی...,NaN,NaN,NaN
3,420,55359965,ظهوری,مجید ظهوری,اجناس کادویی,55359965,NaN,منطقه 16,\r\n م شوش - خ صابونیان...,NaN,NaN,NaN
4,480,09125590480,شیک پوش,دارابی,پوشاک,,NaN,منطقه 15,\r\n 20 متری افسریه - ن...,NaN,NaN,NaN
5,491,33172277,گالری فرش رجب زاده,سعید رجب زاده,بورس انواع فرش و قالیچه کاشان ...,3317227733175498,0912176862109125590491,منطقه 14,\r\n خ پیروزی ، چهارراه...,NaN,NaN,NaN
6,562,44291467,تهیه غذای مجلسی,فرهام شریفی و هادی متولی,تهیه غذا (سرویس رایگان در محدو...,442914684429146709125590562,09121471920,منطقه 2,\r\n ستارخان، بازارچه س...,NaN,NaN,NaN
7,586,33802391,یزدانپور,ابراهیم یزدانپور,لباس زیر,33802391,NaN,منطقه 15,\r\n افسریه - 15 متری د...,NaN,NaN,NaN
8,624,09125590624,اتو سرویس اسلامی نسب,حسن اسلامی نسب,تعویض روغن انواع اتومبیل های ا...,,NaN,حومه تهران,\r\n جاده خاوران -شریف ...,NaN,NaN,NaN
9,633,66291569,صنایع چوبی رستمی,اسحاق رستمی,صنایع چوبی (کمد، جاکفشی ، سروی...,66291569,09125590633,منطقه 18,\r\n شهرک ولیعصر، خ سید...,NaN,NaN,NaN
10,635,66240678,علیزاده,حمید علیزاده,لوازم بهداشتی ساختمانی و رنگ و...,66240678,NaN,منطقه 18,\r\n جاده ساوه - شهرک و...,NaN,NaN,NaN
11,656,55633588,فروشگاه 110,عباس صمدی,عرضه کننده لوازم نفت سوز و گاز...,55633588,NaN,منطقه 12,\r\n بازار بزرگ- اول تی...,NaN,NaN,NaN
12,678,33460222,تراشکاری و سوپاپ تراشی مجهز مسعودیه,مراد حسین گودرزی,تراشکاری,33460222,NaN,منطقه 15,\r\n خ خاوران -مسعودیه ...,NaN,NaN,NaN
13,681,33652426,گروه تخصصی انبوه سازان قائم,مهندس مرتضی حسینی,خرید، فروش، رهن، اجاره، مشارکت...,3365242633146835,09125590681,منطقه 14,\r\n پیروزی، بلوار ابوذ...,NaN,NaN,NaN
14,683,77535493,عطاری خیر خواه,کریم خیر خواه,گیاهان دارویی-عرقیات-ادویه جات...,7753549377650657,NaN,منطقه 7,\r\n خ بهارستان-روبروی ...,NaN,NaN,NaN
15,684,77151139,1661تهران,فوزیه احمدی,دفتراسنادرسمی,77151139,NaN,منطقه 13,\r\n خ دماوند، چهارراه ...,NaN,NaN,NaN
16,698,88172975,کیهان راه,ربیعی,شرکت خدمات مسافرت هوایی و جهان...,2670707588172975,NaN,منطقه 7,\r\n خیابان خرمشهر ، خی...,NaN,NaN,keyhangardi@yahoo.com
17,702,22896584,تن پوش تیتیل,ساسان ارجمند,پوشاک زنانه,22896584,09125590702,منطقه 3,\r\n خ شریعتی - نبش خ ظ...,NaN,NaN,NaN
18,753,33807158,خدمات انژکتوری صمد - تعمیرات برق و انژکتور اتو...,تبرایی,تعمیرات برق و انژکتور اتومبیل ...,33807158,0912764047709125590753,منطقه 15,\r\n تهران ، افسریه ، 1...,NaN,NaN,NaN
19,763,33971106,الکترو صنعت غرب,رضا بهلولی,الکترو موتور - گیربکس - پمپ ها...,33971106339160043605685909125590763,NaN,منطقه 12,\r\n سعدی جنوبی - بالات...,NaN,NaN,electrosanat.gharb@gmail.com
20,840,76242521,هنرکده سی رنگ,میثم حسینلو,آموزش نقاشی,76242521,NaN,حومه تهران,\r\n پردیس پاساژ بهارس...,NaN,NaN,NaN
21,851,33484347,املاک پاسارگاد,مهدی ورمزیار,خرید و فروش - رهن و اجاره - مش...,33484347,NaN,منطقه 15,\r\n مشیریه -30 متری صا...,NaN,NaN,NaN
22,921,09125590921,مهبان,منصور مهربانی,تعمیرگاه,09125590921,NaN,منطقه 20,\r\n شهرری - جاده سوم -...,NaN,NaN,NaN
23,948,55338920,فروشگاه روشن,رضا بصیری,لوازم یدکی اتومبیل,55338920,09125590948,منطقه 13,\r\n خ 17 شهریور جنوبی،...,NaN,NaN,NaN
24,949,88721572,دارکوب آسمان آبی,سمانه صادقی,شرکت خدمات مسافرتی و جهانگردی ...,8872157209125590949,NaN,منطقه 6,\r\n م آرژانتین خ بخارس...,www.daarkoob.net,NaN,darkoob_bluesky@yahoo.com