In [1]:
import requests
from bs4 import BeautifulSoup
import numpy as np
import pandas as pd

In [2]:
team1=[]
team2=[]
results=[]
goal1=[]
goal2=[]

In [3]:
n_of_soccer=10

In [6]:
#تغییر کد403 به 200
headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36'}
for i in range(1,39):
    url="https://top90.ir/england/premier-league/?tpl=schedules&week={}".format(i)
    r = requests.get('{}#!{}'.format(url, 'meme'), headers=headers)
    
    soup=BeautifulSoup(r.content,'html.parser')
    S2=soup.find_all('dd', class_="mElO1")
    S1=soup.find_all('dd',class_="mElO2")
    result=soup.find_all('dd', class_="mElScore")
    for n in range(0,n_of_soccer):
        team2_name=S2[n].find('a').get_text()
        team2.append(team2_name)
    
        team1_name=S1[n].find('a').get_text()
        team1.append(team1_name)
    
        v=result[n].get_text()
        g1=int(v[0])
        goal1.append(g1)
        g2=int(v[4])
        goal2.append(g2)

In [5]:
print(v)

1 - 1

In [6]:
FB=pd.DataFrame({'Visitor_Team': team1,
                  'V_PTS': goal1,
                  'Home_Team': team2,
                  'H_PTS': goal2
    
})

In [7]:
FB[20:30]

     Visitor_Team  V_PTS      Home_Team  H_PTS
20         اورتون      0     استون ویلا      2
21           چلسی      3          نوریچ      2
22     ساوتهمپتون      2        برایتون      0
23  کریستال پالاس      2  منچستریونایتد      1
24       لسترسیتی      2  شفیلد یونایتد      1
25         وستهام      3        واتفورد      1
26         آرسنال      1        لیورپول      3
27     منچسترسیتی      3        بورنموث      1
28        نیوکاسل      1        تاتنهام      0
29          برنلی      1     ولورهمپتون      1

In [8]:
r1=requests.get('https://www.varzesh3.com/table/%D8%AC%D8%AF%D9%88%D9%84-%D8%A7%D9%86%DA%AF%D9%84%DB%8C%D8%B3-2018-2019-%D9%84%DB%8C%DA%AF-%D8%A8%D8%B1%D8%AA%D8%B1')
r1.status_code

200

In [9]:
soup2=BeautifulSoup(r1.content,'html.parser')
name=soup2.find_all('td', class_="t101")
#بازی ها
p=soup2.find_all('td', class_="t201")
#بردها
w=soup2.find_all('td', class_="t301")
#مساوی
d=soup2.find_all('td', class_="t401")
#باخت
l=soup2.find_all('td', class_="t501")
#گل زده
f=soup2.find_all('td', class_="t601")
#گل خورده
a=soup2.find_all('td', class_="t701")
#تفاضل گل
gd=soup2.find_all('td', class_="t801")
#امتیاز
pts=soup2.find_all('td', class_="t901")

In [10]:
#print(pts)

In [11]:
team_names=[]
P=[]
W=[]
D=[]
L=[]
F=[]
A=[]
GD=[]
PTS=[]

In [12]:
for m in range(0,20):
    names=name[m].find('a').get_text()
    team_names.append(names)
    
    p_=p[m].get_text()
    P.append(p_)
    
    w_=w[m].get_text()
    W.append(w_)
    
    d_=d[m].get_text()
    D.append(d_)
    
    l_=l[m].get_text()
    L.append(l_)
    
    f_=f[m].get_text()
    F.append(f_)
    
    a_=a[m].get_text()
    A.append(a_)
    
    gd_=gd[m].get_text()
    GD.append(gd_)
    
    pts_=pts[m].get_text()
    PTS.append(pts_)

In [13]:
PTS[0]

'\r\n                        98\r\n                    '

In [14]:
Ranking=pd.DataFrame({"Team":team_names ,
                     "Rank":PTS ,
                     "GD":GD ,
                     "P":P ,
                     "W":W ,
                     "D":D ,
                     "L":L ,
                     "F":F ,
                     "A":A 
                     })

In [15]:
Ranking[:5]

,Team,Rank,GD,P,W,D,L,F,A
0,منچسترسیتی,\r\n 98\r\n ...,72,38,32,2,4,95,23
1,لیورپول,\r\n 97\r\n ...,67,38,30,7,1,89,22
2,چلسی,\r\n 72\r\n ...,24,38,21,9,8,63,39
3,تاتنهام,\r\n 71\r\n ...,28,38,23,2,13,67,39
4,آرسنال,\r\n 70\r\n ...,22,38,21,7,10,73,51

In [16]:
Ranking['Rank']=Ranking['Rank'].str.replace('\r', '')
Ranking['Rank']=Ranking['Rank'].str.replace('\n', '')
print(type(Ranking['Rank'][0]))
#df['E'] = df['B'].str.replace('\W', '')
Ranking[:5]

<class 'str'>

,Team,Rank,GD,P,W,D,L,F,A
0,منچسترسیتی,98,72,38,32,2,4,95,23
1,لیورپول,97,67,38,30,7,1,89,22
2,چلسی,72,24,38,21,9,8,63,39
3,تاتنهام,71,28,38,23,2,13,67,39
4,آرسنال,70,22,38,21,7,10,73,51

In [17]:
Ranking[["Rank","GD","P", "W","D", "L" ,"F" ,"A"]]=Ranking[["Rank","GD","P", "W","D", "L" ,"F" ,"A"]].apply(pd.to_numeric)
#df[["a", "b"]] = df[["a", "b"]].apply(pd.to_numeric)
type(Ranking["W"][0])

numpy.int64

In [18]:
#target
FB['Homewin']=FB['V_PTS']<FB['H_PTS']
FB.head()[:3]

    Visitor_Team  V_PTS Home_Team  H_PTS  Homewin
0          نوریچ      1   لیورپول      4     True
1     منچسترسیتی      5    وستهام      0    False
2  شفیلد یونایتد      1   بورنموث      1    False

In [19]:
y = FB["Homewin"].values
# V_PTS , H_PTS: leak
x=FB[["Visitor_Team","Home_Team"]].values

In [20]:

print("Home percentage: {0:.1f}%".format(100 *   FB['Homewin'].mean()))

Home percentage: 45.3%

In [21]:
FB["VisitorLastWin"]=False
FB["HomeLastWin"]=False
FB.iloc[:3]

    Visitor_Team  V_PTS Home_Team  H_PTS  Homewin  VisitorLastWin  HomeLastWin
0          نوریچ      1   لیورپول      4     True           False        False
1     منچسترسیتی      5    وستهام      0    False           False        False
2  شفیلد یونایتد      1   بورنموث      1    False           False        False

In [22]:
from collections import defaultdict

In [23]:
won_last=defaultdict(int)
for index,row in FB.iterrows():
    visitorteam=row["Visitor_Team"]
    hometeam=row["Home_Team"]
    row["VisitorLastWin"]=won_last[visitorteam]
    row["HomeLastWin"]=won_last[hometeam]
    FB.iloc[index]=row
    won_last[hometeam]= row['Homewin']
    won_last[visitorteam]= not row['Homewin']
    
FB.iloc[:15]

,Visitor_Team,V_PTS,Home_Team,H_PTS,Homewin,VisitorLastWin,HomeLastWin
0,نوریچ,1,لیورپول,4,True,0,0
1,منچسترسیتی,5,وستهام,0,False,0,0
2,شفیلد یونایتد,1,بورنموث,1,False,0,0
3,ساوتهمپتون,0,برنلی,3,True,0,0
4,اورتون,0,کریستال پالاس,0,False,0,0
5,برایتون,3,واتفورد,0,False,0,0
6,استون ویلا,1,تاتنهام,3,True,0,0
7,ولورهمپتون,0,لسترسیتی,0,False,0,0
8,آرسنال,1,نیوکاسل,0,False,0,0
9,چلسی,0,منچستریونایتد,4,True,0,0
10,برنلی,1,آرسنال,2,True,True,True
11,بورنموث,2,استون ویلا,1,False,False,False
12,وستهام,1,برایتون,1,False,False,True
13,واتفورد,0,اورتون,1,True,False,True
14,نیوکاسل,1,نوریچ,3,True,False,False

In [64]:
#FB.iloc[10:15]

In [33]:
from sklearn.tree import DecisionTreeClassifier
dtc=DecisionTreeClassifier(random_state=42)

from sklearn.model_selection import cross_val_score
x=FB[["VisitorLastWin","HomeLastWin"]].values
scores=cross_val_score(dtc,x,y,scoring='accuracy',cv=5)
print("accuracy : {0:.2f}".format(100* np.mean(scores)))

accuracy : 53.40

In [29]:
FB["Visitorwinstreak"]=0
FB["Homewinstreak"]=0
FB.iloc[0:5]

,Visitor_Team,V_PTS,Home_Team,H_PTS,Homewin,VisitorLastWin,HomeLastWin,Visitorwinstreak,Homewinstreak
0,نوریچ,1,لیورپول,4,True,0,0,0,0
1,منچسترسیتی,5,وستهام,0,False,0,0,0,0
2,شفیلد یونایتد,1,بورنموث,1,False,0,0,0,0
3,ساوتهمپتون,0,برنلی,3,True,0,0,0,0
4,اورتون,0,کریستال پالاس,0,False,0,0,0,0

In [30]:
win_streak=defaultdict(int)

for index,row in FB.iterrows():
    visitorteam=row["Visitor_Team"]
    hometeam=row["Home_Team"]
    row["Visitorwinstreak"]=win_streak[visitorteam]
    row["Homewinstreak"]=win_streak[hometeam]
    FB.iloc[index]=row
    if row["Homewin"]==True:
        win_streak[visitorteam]=0
        win_streak[hometeam]+=1
    else:
        win_streak[hometeam]=0
        win_streak[visitorteam]+=1

In [31]:
FB.iloc[35:40]

,Visitor_Team,V_PTS,Home_Team,H_PTS,Homewin,VisitorLastWin,HomeLastWin,Visitorwinstreak,Homewinstreak
35,واتفورد,1,نیوکاسل,1,False,False,True,0,1
36,نوریچ,0,وستهام,2,True,False,True,0,2
37,لیورپول,3,برنلی,0,False,True,True,3,1
38,ولورهمپتون,2,اورتون,3,True,False,False,0,0
39,تاتنهام,2,آرسنال,2,False,False,False,0,0

In [34]:
dtc=DecisionTreeClassifier(random_state=42)

from sklearn.model_selection import cross_val_score
x=FB[["VisitorLastWin","HomeLastWin","Visitorwinstreak","Homewinstreak"]].values
scores=cross_val_score(dtc,x,y,scoring='accuracy',cv=5)
print("accuracy : {0:.2f}".format(100* np.mean(scores)))

accuracy : 56.57

In [88]:
#x=FB[["Visitorwinstreak","Homewinstreak"]].values
#scores=cross_val_score(dtc,x,y,scoring='accuracy',cv=3)
#print("accuracy : {0:.2f}".format(100* np.mean(scores)))

accuracy : 63.21

In [35]:
print(Ranking[Ranking["Team"]=="تاتنهام"]["Rank"].values[0])

71

In [ ]:
FB['HomeTeamRanksHigher']=0

for index,row in FB.iterrows():
    visitorteam=row["Visitor_Team"]
    hometeam=row["Home_Team"]
    v_Rank=Ranking[Ranking["Team"]==visitorteam]['Rank'].values[0]
    h_Rank=Ranking[Ranking["Team"]==hometeam]['Rank'].values[0]
    row["HomeTeamRanksHigher"]=h_Rank>v_Rank
    FB.iloc[index]=row

In [38]:
FB[20:30]

,Visitor_Team,V_PTS,Home_Team,H_PTS,Homewin,VisitorLastWin,HomeLastWin,Visitorwinstreak,Homewinstreak,HomeTeamRanksHigher
20,اورتون,0,استون ویلا,2,True,True,False,2,0,[]
21,چلسی,3,نوریچ,2,False,False,True,0,1,[]
22,ساوتهمپتون,2,برایتون,0,False,False,False,0,0,[False]
23,کریستال پالاس,2,منچستریونایتد,1,False,False,True,0,2,[True]
24,لسترسیتی,2,شفیلد یونایتد,1,False,True,True,1,2,[]
25,وستهام,3,واتفورد,1,False,True,False,1,0,[False]
26,آرسنال,1,لیورپول,3,True,True,True,2,2,[True]
27,منچسترسیتی,3,بورنموث,1,False,False,True,0,1,[False]
28,نیوکاسل,1,تاتنهام,0,False,False,True,0,2,[]
29,برنلی,1,ولورهمپتون,1,False,False,False,0,0,[True]

In [5]:
FB["HomeTeamGDHigher"]=0

for index,row in FB.iterrows():
    home_team=row["Home_Team"]
    visitor_team=row["Visitor_Team"]
    home_GD=Ranking[Ranking["Team"]==home_team]["GD"].values[0]
    visitor_GD=Ranking[Ranking["Team"]==visitor_team]["GD"].values[0]
    row["HomeTeamGDHigher"]=int(home_GD>visitor_GD)
    FB.iloc[index]=row

In [42]:
FB["H_RK"]=0
FB["V_RK"]=0

In [47]:
Rk=defaultdict(int)

for index, row in FB.iterrows():
    home_team=row["Home_Team"]
    visitor_team=row["Visitor_Team"]
    if row["Homewin"]==True:
        Rk[home_team]+=3
    
    elif row["H_PTS"]==row["V_PTS"]:
        Rk[home_team]+=1
        Rk[visitor_team]+=1
    else:
        Rk[visitor_team]+=3
    row["H_RK"]=Rk[home_team]
    row["V_RK"]=Rk[visitor_team]
    FB.iloc[index]=row

In [50]:
FB.head()

,Visitor_Team,V_PTS,Home_Team,H_PTS,Homewin,VisitorLastWin,HomeLastWin,Visitorwinstreak,Homewinstreak,HomeTeamRanksHigher,H_RK,V_RK
0,نوریچ,1,لیورپول,4,True,0,0,0,0,0,3,0
1,منچسترسیتی,5,وستهام,0,False,0,0,0,0,0,0,3
2,شفیلد یونایتد,1,بورنموث,1,False,0,0,0,0,0,1,1
3,ساوتهمپتون,0,برنلی,3,True,0,0,0,0,0,3,0
4,اورتون,0,کریستال پالاس,0,False,0,0,0,0,0,1,1

In [52]:
FB['V_GD']=0
FB['H_GD']=0

In [55]:
Goals_scored=defaultdict(int)
Goles_eaten=defaultdict(int)

for index, row in FB.iterrows():
    home_team=row["Home_Team"]
    visitor_team=row["Visitor_Team"]
    Goals_scored[home_team]+=row['H_PTS']
    Goals_scored[visitor_team]+=row['V_PTS']
    Goles_eaten[home_team]+=row['V_PTS']
    Goles_eaten[visitor_team]+=row['H_PTS']
    row['V_GD']=(Goals_scored[visitor_team]-Goles_eaten[visitor_team])
    row['H_GD']=(Goals_scored[home_team]-Goles_eaten[home_team])
    FB.iloc[index]=row

In [56]:
FB

,Visitor_Team,V_PTS,Home_Team,H_PTS,Homewin,VisitorLastWin,HomeLastWin,Visitorwinstreak,Homewinstreak,HomeTeamRanksHigher,H_RK,V_RK,V_GD,H_GD
0,نوریچ,1,لیورپول,4,True,0,0,0,0,0,3,0,-3,3
1,منچسترسیتی,5,وستهام,0,False,0,0,0,0,0,0,3,5,-5
2,شفیلد یونایتد,1,بورنموث,1,False,0,0,0,0,0,1,1,0,0
3,ساوتهمپتون,0,برنلی,3,True,0,0,0,0,0,3,0,-3,3
4,اورتون,0,کریستال پالاس,0,False,0,0,0,0,0,1,1,0,0
5,برایتون,3,واتفورد,0,False,0,0,0,0,0,0,3,3,-3
6,استون ویلا,1,تاتنهام,3,True,0,0,0,0,0,3,0,-2,2
7,ولورهمپتون,0,لسترسیتی,0,False,0,0,0,0,0,1,1,0,0
8,آرسنال,1,نیوکاسل,0,False,0,0,0,0,0,0,3,1,-1
9,چلسی,0,منچستریونایتد,4,True,0,0,0,0,0,3,0,-4,4
10,برنلی,1,آرسنال,2,True,True,True,1,1,0,6,3,2,2
11,بورنموث,2,استون ویلا,1,False,False,False,0,0,0,0,4,1,-3
12,وستهام,1,برایتون,1,False,False,True,0,1,0,4,1,-5,3
13,واتفورد,0,اورتون,1,True,False,True,0,1,0,4,0,-4,1
14,نیوکاسل,1,نوریچ,3,True,False,False,0,0,0,3,0,-3,-1
15,لیورپول,2,ساوتهمپتون,1,False,True,False,1,0,0,0,6,4,-4
16,تاتنهام,2,منچسترسیتی,2,False,True,True,1,1,0,4,4,2,5
17,کریستال پالاس,0,شفیلد یونایتد,1,True,False,True,0,1,0,4,1,-1,1
18,لسترسیتی,1,چلسی,1,False,False,False,0,0,0,1,2,0,-4
19,منچستریونایتد,1,ولورهمپتون,1,False,True,True,1,1,0,2,4,4,0
20,اورتون,0,استون ویلا,2,True,True,False,2,0,0,3,4,-1,-1
21,چلسی,3,نوریچ,2,False,False,True,0,1,0,3,4,-3,-2
22,ساوتهمپتون,2,برایتون,0,False,False,False,0,0,0,4,3,-2,1
23,کریستال پالاس,2,منچستریونایتد,1,False,False,True,0,2,0,4,4,0,3
24,لسترسیتی,2,شفیلد یونایتد,1,False,True,True,1,2,0,4,5,1,0
25,وستهام,3,واتفورد,1,False,True,False,1,0,0,0,4,-3,-6
26,آرسنال,1,لیورپول,3,True,True,True,2,2,0,9,6,0,6
27,منچسترسیتی,3,بورنموث,1,False,False,True,0,1,0,4,7,7,-1
28,نیوکاسل,1,تاتنهام,0,False,False,True,0,2,0,4,3,-2,1
29,برنلی,1,ولورهمپتون,1,False,False,False,0,0,0,3,4,2,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
350,نوریچ,0,چلسی,1,True,False,False,0,0,0,63,21,-42,15
351,ولورهمپتون,1,برنلی,1,False,True,True,1,2,0,51,56,11,-8
352,بورنموث,1,منچسترسیتی,2,True,True,True,1,2,0,75,31,-25,58
353,تاتنهام,3,نیوکاسل,1,False,True,False,3,0,0,43,55,11,-18
354,لیورپول,1,آرسنال,2,True,False,False,0,0,0,53,93,48,8
355,استون ویلا,1,اورتون,1,False,True,False,1,0,0,46,31,-27,-11
356,شفیلد یونایتد,0,لسترسیتی,2,True,True,False,4,0,0,62,54,3,31
357,منچستریونایتد,2,کریستال پالاس,0,False,False,False,0,0,0,42,62,28,-17
358,برایتون,1,ساوتهمپتون,1,False,False,True,0,4,0,46,37,-16,-13
359,واتفورد,1,وستهام,3,True,True,True,2,1,0,37,34,-23,-13
360,برنلی,2,نوریچ,0,False,False,False,0,0,0,21,54,-6,-44
361,ساوتهمپتون,2,بورنموث,0,False,False,False,0,0,0,31,49,-11,-27
362,لسترسیتی,0,تاتنهام,3,True,True,True,1,4,0,58,62,28,14
363,نیوکاسل,0,برایتون,0,False,False,True,0,1,0,38,44,-18,-16
364,اورتون,1,شفیلد یونایتد,0,False,False,False,0,0,0,54,49,-10,2
365,کریستال پالاس,0,ولورهمپتون,2,True,False,True,0,2,0,59,42,-19,13
366,منچسترسیتی,4,واتفورد,0,False,True,False,3,0,0,34,78,62,-27
367,آرسنال,0,استون ویلا,1,True,True,True,1,2,0,34,53,7,-26
368,وستهام,1,منچستریونایتد,1,False,True,True,2,1,0,63,38,-13,28
369,چلسی,3,لیورپول,5,True,True,False,1,0,0,96,63,13,50
370,واتفورد,2,آرسنال,3,True,False,False,0,0,0,56,34,-28,8
371,برایتون,2,برنلی,1,False,False,True,0,1,0,54,41,-15,-7
372,ولورهمپتون,0,چلسی,2,True,True,False,3,0,0,66,59,11,15
373,تاتنهام,1,کریستال پالاس,1,False,True,False,5,0,0,43,59,14,-19
374,بورنموث,3,اورتون,1,False,False,True,0,1,0,49,34,-25,-12
375,منچستریونایتد,2,لسترسیتی,0,False,False,False,0,0,0,62,66,30,26
376,نوریچ,0,منچسترسیتی,5,True,False,True,0,4,0,81,21,-49,67
377,لیورپول,3,نیوکاسل,1,False,True,True,1,1,0,44,99,52,-20
378,شفیلد یونایتد,1,ساوتهمپتون,3,True,False,True,0,1,0,52,54,0,-9
379,استون ویلا,1,وستهام,1,False,True,True,3,3,0,39,35,-26,-13

In [4]:
for i in range(0,39):
    url="https://top90.ir/england/premier-league/?tpl=schedules&week={}".format(i)
    print(url)

https://top90.ir/england/premier-league/?tpl=schedules&week=0
https://top90.ir/england/premier-league/?tpl=schedules&week=1
https://top90.ir/england/premier-league/?tpl=schedules&week=2
https://top90.ir/england/premier-league/?tpl=schedules&week=3
https://top90.ir/england/premier-league/?tpl=schedules&week=4
https://top90.ir/england/premier-league/?tpl=schedules&week=5
https://top90.ir/england/premier-league/?tpl=schedules&week=6
https://top90.ir/england/premier-league/?tpl=schedules&week=7
https://top90.ir/england/premier-league/?tpl=schedules&week=8
https://top90.ir/england/premier-league/?tpl=schedules&week=9
https://top90.ir/england/premier-league/?tpl=schedules&week=10
https://top90.ir/england/premier-league/?tpl=schedules&week=11
https://top90.ir/england/premier-league/?tpl=schedules&week=12
https://top90.ir/england/premier-league/?tpl=schedules&week=13
https://top90.ir/england/premier-league/?tpl=schedules&week=14
https://top90.ir/england/premier-league/?tpl=schedules&week=15
https://top90.ir/england/premier-league/?tpl=schedules&week=16
https://top90.ir/england/premier-league/?tpl=schedules&week=17
https://top90.ir/england/premier-league/?tpl=schedules&week=18
https://top90.ir/england/premier-league/?tpl=schedules&week=19
https://top90.ir/england/premier-league/?tpl=schedules&week=20
https://top90.ir/england/premier-league/?tpl=schedules&week=21
https://top90.ir/england/premier-league/?tpl=schedules&week=22
https://top90.ir/england/premier-league/?tpl=schedules&week=23
https://top90.ir/england/premier-league/?tpl=schedules&week=24
https://top90.ir/england/premier-league/?tpl=schedules&week=25
https://top90.ir/england/premier-league/?tpl=schedules&week=26
https://top90.ir/england/premier-league/?tpl=schedules&week=27
https://top90.ir/england/premier-league/?tpl=schedules&week=28
https://top90.ir/england/premier-league/?tpl=schedules&week=29
https://top90.ir/england/premier-league/?tpl=schedules&week=30
https://top90.ir/england/premier-league/?tpl=schedules&week=31
https://top90.ir/england/premier-league/?tpl=schedules&week=32
https://top90.ir/england/premier-league/?tpl=schedules&week=33
https://top90.ir/england/premier-league/?tpl=schedules&week=34
https://top90.ir/england/premier-league/?tpl=schedules&week=35
https://top90.ir/england/premier-league/?tpl=schedules&week=36
https://top90.ir/england/premier-league/?tpl=schedules&week=37
https://top90.ir/england/premier-league/?tpl=schedules&week=38